language: go

go:
    - 1.7
    - 1.8
    - 1.9
    - master

before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y libpcap0.8 libpcap0.8-dev

install:
    - go get github.com/google/gopacket
    - go get github.com/google/gopacket/layers
    - go get github.com/google/gopacket/pcap
    - go get github.com/google/gopacket/pcapgo
    - go get golang.org/x/sync/errgroup

# coveralls.io
after_success:
    - go get golang.org/x/tools/cmd/cover
    - go get github.com/mattn/goveralls
    - $GOPATH/bin/goveralls -service=travis-ci
