language: go

go:
    - 1.7
    - 1.8
    - master

before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y libpcap0.8 libpcap0.8-dev

install:
    - go get github.com/google/gopacket
    - go get github.com/google/gopacket/layers
    - go get github.com/google/gopacket/pcap
